feat: Adding architecture definition module and additional folders variable
Azure/accelerator-bootstrap-modules pull request #35
Opened 2024-09-10 22:00 UTC by sdeguchi

## Overview/Summary

Adding architecture definition module for FSI/SLZ, and additional_folders, enable_alz, and architecture_definition_path hidden variables

## This PR fixes/adds/changes/removes

1. Adds support for including additional folders to repo
2. Adds architecture definition creation module
3. Adds hidden variables to include alz archetypes in architecture definition template file(enable_alz), architecture definition file path(architecture_definition_path), and include additional folders in repo(additional_folders)

### Breaking Changes

1. None

## Testing Evidence

<img width="1137" alt="local_fsi1" src="https://github.com/user-attachments/assets/798eea9d-544a-483f-9d4f-1689e13eb558">

<img width="1210" alt="github_fsi1" src="https://github.com/user-attachments/assets/dcb58a96-bb45-408f-8517-069454acae03">

<img width="1065" alt="ado_fsi1" src="https://github.com/user-attachments/assets/a4405e5e-670d-4839-9863-4e75948af890">

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/alz-terraform-accelerator/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/alz-terraform-accelerator/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/alz-terraform-accelerator/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

2024-09-10 22:04 UTC, sdeguchi commented
@microsoft-github-policy-service agree company="Microsoft"

2024-09-11 09:06 UTC, jaredfholgate requested changes
Need to remove reference to deprecated provider

2024-09-11 09:06 UTC, jaredfholgate commented on modules/template_architecture_definition/data.tf
> +data "template_file" "populated_architecture_definition_json" {
Can we change this to use the `template_file` function and remove the reference to the deprecated `template` provider?

This provider is not supported and does not work with macos.

2024-09-11 20:04 UTC, jaredfholgate approved these changes
LGTM

2024-09-11 20:04 UTC, merged